name: TreeAssist
main: me.itsatacoshop247.TreeAssist.TreeAssist
version: 5.5.5
author: itsatacoshop247
description: TreeAssist
dev-url: http://dev.bukkit.org/server-mods/tree-assist/
commands:
  TreeAssist:
    description: Turn TreeAssist Featues on or off
    usage: /<command> toggle/global/debug
permissions:
  treeassist.destroy.*:
    description: allows to use tree-assist for all trees
    children:
      treeassist.destroy.birch: true
      treeassist.destroy.jungle: true
      treeassist.destroy.oak: true
      treeassist.destroy.spruce: true
    default: true
  treeassist.destroy.birch:
    description: allows to use tree-assist for birch trees
    default: true
  treeassist.destroy.jungle:
    description: allows to use tree-assist for jungle trees
    default: true
  treeassist.destroy.oak:
    description: allows to use tree-assist for oak trees
    default: true
  treeassist.destroy.spruce:
    description: allows to use tree-assist for spruce trees
    default: true